"""add file_hash to documentos

Revision ID: 01173443bc85
Revises: ec454f2dca13
Create Date: 2026-03-30 19:33:41.727892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01173443bc85'
down_revision: Union[str, None] = 'ec454f2dca13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentos', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_documentos_file_hash'), 'documentos', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documentos_file_hash'), table_name='documentos')
    op.drop_column('documentos', 'file_hash')
    # ### end Alembic commands ###
