"""add risk_score risk_level risk_calculated_at to clientes

Revision ID: 15c111649cad
Revises: b18b623a3403
Create Date: 2026-03-31 00:43:54.988825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15c111649cad'
down_revision: Union[str, None] = 'b18b623a3403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('risk_score', sa.Float(), nullable=True))
    op.add_column('clientes', sa.Column('risk_level', sa.String(length=10), nullable=True))
    op.add_column('clientes', sa.Column('risk_calculated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'risk_calculated_at')
    op.drop_column('clientes', 'risk_level')
    op.drop_column('clientes', 'risk_score')
    # ### end Alembic commands ###
