"""add rentabilidad_mensual table

Revision ID: 384451a23849
Revises: 3a64405641fa
Create Date: 2026-03-31 00:27:19.725248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '384451a23849'
down_revision: Union[str, None] = '3a64405641fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rentabilidad_mensual',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('honorario', sa.Float(), nullable=False),
    sa.Column('horas_reales', sa.Float(), nullable=False),
    sa.Column('horas_estimadas', sa.Float(), nullable=True),
    sa.Column('rentabilidad_hora', sa.Float(), nullable=True),
    sa.Column('tareas_completadas', sa.Integer(), nullable=False),
    sa.Column('tareas_demoradas', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rentabilidad_mensual')
    # ### end Alembic commands ###
