"""add horas_estimadas horas_reales to tareas

Revision ID: 3a64405641fa
Revises: 01173443bc85
Create Date: 2026-03-31 00:21:24.808846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a64405641fa'
down_revision: Union[str, None] = '01173443bc85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tareas', sa.Column('horas_estimadas', sa.Float(), nullable=True))
    op.add_column('tareas', sa.Column('horas_reales', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tareas', 'horas_reales')
    op.drop_column('tareas', 'horas_estimadas')
    # ### end Alembic commands ###
