"""add alertas_vencimiento and documentos_requeridos tables

Revision ID: b18b623a3403
Revises: 384451a23849
Create Date: 2026-03-31 00:37:41.259056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b18b623a3403'
down_revision: Union[str, None] = '384451a23849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos_requeridos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_vencimiento', sa.String(length=50), nullable=False),
    sa.Column('tipo_documento', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alertas_vencimiento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vencimiento_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.String(length=15), nullable=False),
    sa.Column('dias_restantes', sa.Integer(), nullable=False),
    sa.Column('documentos_faltantes', sa.JSON(), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('vista', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('resuelta_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['vencimiento_id'], ['vencimientos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Seed: mapeo base de documentos requeridos por tipo de vencimiento
    doc_req = sa.table(
        "documentos_requeridos",
        sa.column("tipo_vencimiento", sa.String),
        sa.column("tipo_documento", sa.String),
        sa.column("descripcion", sa.String),
    )
    op.bulk_insert(doc_req, [
        {"tipo_vencimiento": "iva", "tipo_documento": "factura", "descripcion": "Facturas del período"},
        {"tipo_vencimiento": "iva", "tipo_documento": "ddjj", "descripcion": "Declaración jurada IVA"},
        {"tipo_vencimiento": "iibb", "tipo_documento": "factura", "descripcion": "Facturas del período"},
        {"tipo_vencimiento": "iibb", "tipo_documento": "ddjj", "descripcion": "Declaración jurada IIBB"},
        {"tipo_vencimiento": "ganancias", "tipo_documento": "balance", "descripcion": "Balance contable"},
        {"tipo_vencimiento": "ganancias", "tipo_documento": "ddjj", "descripcion": "Declaración jurada ganancias"},
        {"tipo_vencimiento": "monotributo", "tipo_documento": "factura", "descripcion": "Facturas del período"},
        {"tipo_vencimiento": "sueldos_cargas", "tipo_documento": "liquidacion_sueldo", "descripcion": "Liquidaciones de sueldos"},
        {"tipo_vencimiento": "ddjj_anual", "tipo_documento": "balance", "descripcion": "Balance anual"},
        {"tipo_vencimiento": "ddjj_anual", "tipo_documento": "ddjj", "descripcion": "Declaración jurada anual"},
        {"tipo_vencimiento": "bienes_personales", "tipo_documento": "balance", "descripcion": "Balance para bienes personales"},
        {"tipo_vencimiento": "bienes_personales", "tipo_documento": "ddjj", "descripcion": "Declaración jurada bienes personales"},
        {"tipo_vencimiento": "autonomos", "tipo_documento": "recibo", "descripcion": "Recibos de honorarios"},
        {"tipo_vencimiento": "autonomos", "tipo_documento": "ddjj", "descripcion": "Declaración jurada autónomos"},
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alertas_vencimiento')
    op.drop_table('documentos_requeridos')
    # ### end Alembic commands ###
