"""add plantillas_vencimiento table and plantilla_aplicada field

Revision ID: bb3aae8df077
Revises: fbcfb40b3de5
Create Date: 2026-03-28 16:22:40.119908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb3aae8df077'
down_revision: Union[str, None] = 'fbcfb40b3de5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Agregar valor al enum condicionfiscal (PostgreSQL 12+ soporta esto en transacción)
    op.execute("ALTER TYPE condicionfiscal ADD VALUE IF NOT EXISTS 'autonomos'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('plantilla_aplicada', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'plantilla_aplicada')
    # Nota: PostgreSQL no permite eliminar valores de un enum con ALTER TYPE DROP VALUE
    # ### end Alembic commands ###
