"""telegram_chat_id bigint

Revision ID: ec43e60942ec
Revises: ff0421bad1be
Create Date: 2026-04-05 09:26:59.475165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec43e60942ec'
down_revision: Union[str, None] = 'ff0421bad1be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alertas_vencimiento', sa.Column('sent_via_telegram', sa.Boolean(), nullable=False))
    op.add_column('alertas_vencimiento', sa.Column('sent_via_email', sa.Boolean(), nullable=False))
    op.add_column('alertas_vencimiento', sa.Column('telegram_sent_at', sa.DateTime(), nullable=True))
    op.add_column('alertas_vencimiento', sa.Column('email_sent_at', sa.DateTime(), nullable=True))
    op.add_column('clientes', sa.Column('risk_explanation', sa.Text(), nullable=True))
    op.add_column('rentabilidad_mensual', sa.Column('costo_estimado', sa.Float(), nullable=True))
    op.add_column('rentabilidad_mensual', sa.Column('profit_margin_percentage', sa.Float(), nullable=True))
    op.alter_column('studio_config', 'telegram_chat_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.add_column('tareas', sa.Column('tiempo_estimado_min', sa.Integer(), nullable=True))
    op.add_column('tareas', sa.Column('tiempo_real_min', sa.Integer(), nullable=False))
    op.add_column('tareas', sa.Column('proceso_instancia_paso_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tareas', 'proceso_pasos_instancia', ['proceso_instancia_paso_id'], ['id'])
    op.drop_column('tareas', 'tiempo_estimado')
    op.drop_column('tareas', 'tiempo_real')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tareas', sa.Column('tiempo_real', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tareas', sa.Column('tiempo_estimado', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tareas', type_='foreignkey')
    op.drop_column('tareas', 'proceso_instancia_paso_id')
    op.drop_column('tareas', 'tiempo_real_min')
    op.drop_column('tareas', 'tiempo_estimado_min')
    op.alter_column('studio_config', 'telegram_chat_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('rentabilidad_mensual', 'profit_margin_percentage')
    op.drop_column('rentabilidad_mensual', 'costo_estimado')
    op.drop_column('clientes', 'risk_explanation')
    op.drop_column('alertas_vencimiento', 'email_sent_at')
    op.drop_column('alertas_vencimiento', 'telegram_sent_at')
    op.drop_column('alertas_vencimiento', 'sent_via_email')
    op.drop_column('alertas_vencimiento', 'sent_via_telegram')
    # ### end Alembic commands ###
