"""add tiempo_real, capacidad_horas_mes, honorarios, satisfaccion, fecha_baja, documentos table

Revision ID: ec454f2dca13
Revises: b73b03eac462
Create Date: 2026-03-28 17:36:44.205451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec454f2dca13'
down_revision: Union[str, None] = 'b73b03eac462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('vencimiento_id', sa.Integer(), nullable=True),
    sa.Column('nombre_original', sa.String(length=255), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=500), nullable=False),
    sa.Column('tipo_documento', sa.Enum('factura', 'liquidacion_sueldo', 'ddjj', 'recibo', 'extracto_bancario', 'balance', 'contrato', 'otro', name='tipodocumento'), nullable=False),
    sa.Column('confianza', sa.Float(), nullable=True),
    sa.Column('resumen', sa.Text(), nullable=True),
    sa.Column('metadatos', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'procesado', 'requiere_revision', 'error', name='estadodocumento'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['vencimiento_id'], ['vencimientos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('clientes', sa.Column('honorarios_mensuales', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('clientes', sa.Column('satisfaccion', sa.Integer(), nullable=True))
    op.add_column('clientes', sa.Column('fecha_baja', sa.DateTime(), nullable=True))
    op.add_column('empleados', sa.Column('capacidad_horas_mes', sa.Integer(), nullable=False))
    op.add_column('tareas', sa.Column('tiempo_real', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tareas', 'tiempo_real')
    op.drop_column('empleados', 'capacidad_horas_mes')
    op.drop_column('clientes', 'fecha_baja')
    op.drop_column('clientes', 'satisfaccion')
    op.drop_column('clientes', 'honorarios_mensuales')
    op.drop_table('documentos')
    # ### end Alembic commands ###
