"""add contador_asignado_id y tiempo_estimado

Revision ID: fbcfb40b3de5
Revises: 
Create Date: 2026-03-28 14:03:08.341907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbcfb40b3de5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('contador_asignado_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clientes', 'empleados', ['contador_asignado_id'], ['id'])
    op.add_column('tareas', sa.Column('tiempo_estimado', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tareas', 'tiempo_estimado')
    op.drop_constraint(None, 'clientes', type_='foreignkey')
    op.drop_column('clientes', 'contador_asignado_id')
    # ### end Alembic commands ###
